import yaml from 'js-yaml'
import * as fs from 'fs'

const headerImport = `
import {Header} from '../../../components/header/header.tsx'
import styles from '../Blog.module.css'

<div className={styles.body}>
  <Header />
  <div className={styles.container}>
    $INJECTION_PLACEHOLDER
  </div>
</div>

`

const blogTemplate = `
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {Header} from '../../components/header/header'
import {PostOverview} from '../../components/posts/post-overview'
import styles from './Blog.module.css'

const Blog: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Header />
        <h1 className={styles.title}>Latest</h1>
        <p className={styles.description}>A blog about the development of a bluetooth guitar pedal. Also covers product & feature announcements.</p>
        $INJECTION_PLACEHOLDER
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Blog
`

const overviewTemplate = ({title, overview, slug}) => `       <PostOverview title={'${title}'} overview={'${overview}'} slug={'blog/posts/${slug}'} />`

const main = async () => {
  const dir = '../pages/blog/'
  const gen_dir = dir + 'posts/'
  fs.rmSync(gen_dir, { recursive: true, force: true })
  fs.mkdirSync(gen_dir)
  const post_dir = dir + 'posts_src/'

  const files = fs.readdirSync(post_dir)

  const overviews = []

  for (const file of files) {
    if (file.includes('.mdx')) {
      const fileContents = fs.readFileSync(post_dir + file, {encoding:'utf8', flag:'r'})
      const frontMatter = yaml.loadAll(fileContents)
      const markdown = fileContents.replace(/---(.|\n)*?---/, '')
      const output = headerImport.replace('$INJECTION_PLACEHOLDER', markdown)
      fs.writeFileSync(gen_dir + file, output)

      overviews.push(overviewTemplate(frontMatter[0]))

    }
  }

  const overviewString = overviews.reduce((prev: string, curr: string) => prev + '\n' + curr, '')
  const blog = blogTemplate.replace('$INJECTION_PLACEHOLDER', overviewString)
  fs.writeFileSync('../pages/blog/index.tsx', blog)

}

main()

