import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {PostOverview} from './components/posts/post-overview.tsx'
import styles from './Blog.module.css'

const Blog: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h3>Bluebox blog</h3>
        <p>A blog about the development of a bluetooth guitar pedal. Also covers product & feature announcements.</p>
        <PostOverview />
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Blog
